# SPDX-FileCopyrightText: 2025 Dominik Wombacher <dominik@wombacher.cc>
#
# SPDX-License-Identifier: MIT-0

template-file-path: cfn/scp-cost-ec2.yaml
parameters:
  OrganizationRootId: r-lp71
tags:
  Purpose: AWSOrg
  Lifecycle: Active
  Environment: Production
  Creator: CloudFormation
