# SPDX-FileCopyrightText: 2025 Dominik Wombacher <dominik@wombacher.cc>
#
# SPDX-License-Identifier: Apache-2.0

AWSTemplateFormatVersion: '2010-09-09'
Description: "Budget and Cost Anomaly Detection for AWS Organizations"

Parameters:
  AlertSnsTopicArn:
    Type: String
    Description: SNS topic ARN for budget and cost anomaly alerts

Resources:
  # Monthly cost budget with alerts at 75% and 100% thresholds
  # Why: Proactive cost monitoring to prevent billing surprises
  MonthlyCostBudget:
    DeletionPolicy: Retain
    UpdateReplacePolicy: Retain
    Type: AWS::Budgets::Budget
    Properties:
      Budget:
        BudgetName: Default Cost Budget
        BudgetLimit:
          Amount: 10
          Unit: USD
        TimeUnit: MONTHLY
        BudgetType: COST
      NotificationsWithSubscribers:
        - Notification:
            NotificationType: FORECASTED
            ComparisonOperator: GREATER_THAN
            Threshold: 75
            ThresholdType: PERCENTAGE
          Subscribers:
            - SubscriptionType: SNS
              Address: !Ref AlertSnsTopicArn
        - Notification:
            NotificationType: ACTUAL
            ComparisonOperator: GREATER_THAN
            Threshold: 75
            ThresholdType: PERCENTAGE
          Subscribers:
            - SubscriptionType: SNS
              Address: !Ref AlertSnsTopicArn
        - Notification:
            NotificationType: FORECASTED
            ComparisonOperator: GREATER_THAN
            Threshold: 100
            ThresholdType: PERCENTAGE
          Subscribers:
            - SubscriptionType: SNS
              Address: !Ref AlertSnsTopicArn
        - Notification:
            NotificationType: ACTUAL
            ComparisonOperator: GREATER_THAN
            Threshold: 100
            ThresholdType: PERCENTAGE
          Subscribers:
            - SubscriptionType: SNS
              Address: !Ref AlertSnsTopicArn

  # Cost anomaly detection for all AWS services
  # Why: Free ML-powered anomaly detection to catch unexpected cost spikes
  CostAnomalyDefaultServicesMonitor:
    DeletionPolicy: Retain
    UpdateReplacePolicy: Retain
    Type: AWS::CE::AnomalyMonitor
    Properties:
      MonitorName: Default-Services-Monitor
      MonitorType: DIMENSIONAL
      MonitorDimension: SERVICE

  # Cost anomaly subscription for sns topic
  # Why: Get notified of cost anomalies above $5 threshold
  CostAnomalyDefaultServicesSubscription:
    DeletionPolicy: Retain
    UpdateReplacePolicy: Retain
    Type: AWS::CE::AnomalySubscription
    Properties:
      SubscriptionName: Default-Services-Subscription
      Frequency: IMMEDIATE
      MonitorArnList:
        - !Ref CostAnomalyDefaultServicesMonitor
      Subscribers:
        - Type: SNS
          Address: !Ref AlertSnsTopicArn
      ThresholdExpression: |
        {
          "Dimensions": {
            "Key": "ANOMALY_TOTAL_IMPACT_PERCENTAGE",
            "MatchOptions": [ "GREATER_THAN_OR_EQUAL" ],
            "Values": [ "10" ]
          }
        }

Outputs:
  MonthlyCostBudgetId:
    Description: Monthly Cost Budget ID
    Value: !Ref MonthlyCostBudget
    Export:
      Name: !Sub "${AWS::StackName}-MonthlyCostBudget-Id"

  CostAnomalyDefaultServicesMonitorId:
    Description: Serverless Cost Anomaly Monitor ID
    Value: !Ref CostAnomalyDefaultServicesMonitor
    Export:
      Name: !Sub "${AWS::StackName}-CostAnomalyDefaultServicesMonitor-Id"

  CostAnomalyDefaultServicesSubscriptionId:
    Description: Cost Anomaly Subscription ID
    Value: !Ref CostAnomalyDefaultServicesSubscription
    Export:
      Name: !Sub "${AWS::StackName}-CostAnomalyDefaultServicesSubscription-Id"
