# SPDX-FileCopyrightText: 2025 Dominik Wombacher <dominik@wombacher.cc>
#
# SPDX-License-Identifier: MIT-0

AWSTemplateFormatVersion: '2010-09-09'
Description: "IAM roles for AWS CloudFormation operations including Organizations management and Git sync functionality"

Parameters:
  GitSyncConnectionId:
    Type: String
    Description: CodeConnections connection ID for Git sync
    Default: "b01ca462-169e-42ce-a10c-ccb09a3ca0e7"

Resources:
  # Allows CloudFormation to create and manage SCPs, RCPs, and other org policies
  CloudFormationOrgRole:
    DeletionPolicy: Retain
    UpdateReplacePolicy: Retain
    Type: AWS::IAM::Role
    Properties:
      RoleName: CustomerServiceRoleForCloudformationInfraAWSOrg
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: cloudformation.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: CustomerPolicyForCloudformationInfraAWSOrg
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Sid: OrganizationsPolicies
                Effect: Allow
                Action:
                  - organizations:AttachPolicy
                  - organizations:CreatePolicy
                  - organizations:DeletePolicy
                  - organizations:DescribeAccount
                  - organizations:DescribeCreateAccountStatus
                  - organizations:DescribeEffectivePolicy
                  - organizations:DescribeOrganization
                  - organizations:DescribeOrganizationalUnit
                  - organizations:DescribePolicy
                  - organizations:DetachPolicy
                  - organizations:DisableAWSServiceAccess
                  - organizations:DisablePolicyType
                  - organizations:EnableAWSServiceAccess
                  - organizations:EnablePolicyType
                  - organizations:ListAccounts
                  - organizations:ListAccountsForParent
                  - organizations:ListAWSServiceAccessForOrganization
                  - organizations:ListCreateAccountStatus
                  - organizations:ListOrganizationalUnitsForParent
                  - organizations:ListParents
                  - organizations:ListPolicies
                  - organizations:ListPoliciesForTarget
                  - organizations:ListRoots
                  - organizations:ListTargetsForPolicy
                  - organizations:UpdatePolicy
                  - organizations:TagResource
                  - organizations:ListTagsForResource
                Resource: "*"
              - Sid: BudgetsManagement
                Effect: Allow
                Action:
                  - budgets:ModifyBudget
                  - budgets:ViewBudget
                  - budgets:TagResource
                  - budgets:ListTagsForResource
                Resource: "*"
              - Sid: CostAnomalyDetection
                Effect: Allow
                Action:
                  - ce:CreateAnomalyMonitor
                  - ce:UpdateAnomalyMonitor
                  - ce:DeleteAnomalyMonitor
                  - ce:GetAnomalyMonitors
                  - ce:CreateAnomalySubscription
                  - ce:UpdateAnomalySubscription
                  - ce:DeleteAnomalySubscription
                  - ce:GetAnomalySubscriptions
                  - ce:TagResource
                  - ce:ListTagsForResource
                Resource: "*"
              - Sid: CloudFormationManagement
                Effect: Allow
                Action:
                  - cloudformation:CreateChangeSet
                  - cloudformation:CreateStack
                  - cloudformation:DeleteChangeSet
                  - cloudformation:DeleteStack
                  - cloudformation:DescribeChangeSet
                  - cloudformation:DescribeStackEvents
                  - cloudformation:DescribeStackResources
                  - cloudformation:DescribeStacks
                  - cloudformation:ExecuteChangeSet
                  - cloudformation:GetTemplate
                  - cloudformation:ListChangeSets
                  - cloudformation:ListStacks
                  - cloudformation:UpdateStack
                  - cloudformation:ValidateTemplate
                  - cloudformation:GetTemplateSummary
                Resource: "*"

  # Allows CodeConnections to sync Git repositories with CloudFormation stacks
  CloudFormationGitSyncRole:
    DeletionPolicy: Retain
    UpdateReplacePolicy: Retain
    Type: AWS::IAM::Role
    Properties:
      RoleName: CustomerServiceRoleForCloudformationInfraAWSOrgGitSync
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Sid: CfnGitSyncTrustPolicy
            Effect: Allow
            Principal:
              Service: cloudformation.sync.codeconnections.amazonaws.com
            Action: sts:AssumeRole
            Condition:
              StringEquals:
                aws:SourceAccount: !Ref AWS::AccountId
              ArnLike:
                aws:SourceArn: !Sub "arn:aws:codeconnections:${AWS::Region}:${AWS::AccountId}:connection/${GitSyncConnectionId}"
      Policies:
        - PolicyName: CustomerPolicyForCloudformationInfraAWSOrgGitSync
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Sid: SyncToCloudFormation
                Effect: Allow
                Action:
                  - cloudformation:CreateChangeSet
                  - cloudformation:DeleteChangeSet
                  - cloudformation:DescribeChangeSet
                  - cloudformation:DescribeStackEvents
                  - cloudformation:DescribeStacks
                  - cloudformation:ExecuteChangeSet
                  - cloudformation:GetTemplate
                  - cloudformation:ListChangeSets
                  - cloudformation:ListStacks
                  - cloudformation:ValidateTemplate
                Resource: "*"
              - Sid: PolicyForManagedRules
                Effect: Allow
                Action:
                  - events:PutRule
                  - events:PutTargets
                Resource: "*"
                Condition:
                  StringEquals:
                    events:ManagedBy:
                      - cloudformation.sync.codeconnections.amazonaws.com
              - Sid: PolicyForDescribingRule
                Effect: Allow
                Action: events:DescribeRule
                Resource: "*"

Outputs:
  CloudFormationOrgRoleArn:
    Description: ARN of the CloudFormation Organizations management role
    Value: !GetAtt CloudFormationOrgRole.Arn
    Export:
      Name: !Sub "${AWS::StackName}-CloudFormationOrgRole-Arn"

  CloudFormationGitSyncRoleArn:
    Description: ARN of the CloudFormation Git sync role
    Value: !GetAtt CloudFormationGitSyncRole.Arn
    Export:
      Name: !Sub "${AWS::StackName}-CloudFormationGitSyncRole-Arn"
