# SPDX-FileCopyrightText: 2025 Dominik Wombacher <dominik@wombacher.cc>
#
# SPDX-License-Identifier: MIT-0

AWSTemplateFormatVersion: '2010-09-09'
Description: "Resource Control Policies for AWS Organizations - encryption, secure transport, org-only access, OIDC restrictions"

Parameters:
  OrganizationId:
    Type: String
    Description: "AWS Organizations ID (e.g., o-xxxxxxxxxx)"
  OrganizationRootId:
    Type: String
    Description: "AWS Organizations root ID (e.g., r-xxxx)"
  GitHubRepo:
    Type: String
    Description: "GitHub repository allowed for OIDC (format: org/repo or org/* for all repos)"

Resources:
  # RCP for security and compliance
  # Why: Enforces encryption, secure transport, and organization-only access
  ResourceControlPolicies:
    DeletionPolicy: Retain
    UpdateReplacePolicy: Retain
    Type: AWS::Organizations::Policy
    Properties:
      Type: RESOURCE_CONTROL_POLICY
      Name: ResourceControlPolicies
      Description: |
        RCP for security and compliance (encryption, secure transport, org-only access, OIDC restrictions).
        See: https://docs.aws.amazon.com/IAM/latest/UserGuide/best-practices.html
      Content:
        Version: 2012-10-17
        Statement:
          - Sid: EnforceSecureTransport
            Effect: Deny
            Principal: '*'
            Action:
              - 'sts:*'
              - 's3:*'
              - 'sqs:*'
              - 'secretsmanager:*'
              - 'kms:*'
            Resource: '*'
            Condition:
              BoolIfExists:
                'aws:SecureTransport': 'false'
          - Sid: EnforceS3TlsVersion
            Effect: Deny
            Principal: '*'
            Action:
              - 's3:*'
            Resource: '*'
            Condition:
              NumericLessThan:
                's3:TlsVersion':
                  - '1.2'
          - Sid: EnforceEncryption
            Effect: Deny
            Principal: '*'
            Action:
              - 's3:PutObject'
            Resource: '*'
            Condition:
              'Null':
                's3:x-amz-server-side-encryption': 'true'
          - Sid: DenyS3PublicAccess
            Effect: Deny
            Principal: '*'
            Action:
              - 's3:PutBucketAcl'
              - 's3:PutBucketPolicy'
              - 's3:PutObjectAcl'
            Resource: '*'
            Condition:
              StringEquals:
                's3:x-amz-acl':
                  - 'public-read'
                  - 'public-read-write'
                  - 'authenticated-read'
          # https://aws.amazon.com/blogs/aws/introducing-resource-control-policies-rcps-a-new-authorization-policy/
          # https://docs.aws.amazon.com/organizations/latest/userguide/orgs_manage_policies_rcps.html
          - Sid: EnforceOrgIdentities
            Effect: Deny
            Principal: '*'
            # RCPs are available in all commercial AWS Regions and, at launch, the following services are supported:
            # Amazon Simple Storage Service (Amazon S3), AWS Security Token Service (AWS STS),
            # AWS Key Management Service (AWS KMS), Amazon Simple Queue Service (Amazon SQS), and AWS Secrets Manager.
            # https://docs.aws.amazon.com/organizations/latest/userguide/orgs_manage_policies_rcps_syntax.html#rcp-syntax-action
            Action:
              - 's3:*'
              - 'sts:*'
              - 'kms:*'
              - 'sqs:*'
              - 'secretsmanager:*'
              - 'ecr:*'
              - 'aoss:*'
            Resource: '*'
            Condition:
              StringNotEqualsIfExists:
                'aws:PrincipalOrgID': !Ref OrganizationId
              BoolIfExists:
                'aws:PrincipalIsAWSService': 'false'
      TargetIds:
        - !Ref OrganizationRootId

  RCPRestrictOIDCToApprovedProviders:
    DeletionPolicy: Retain
    UpdateReplacePolicy: Retain
    Type: AWS::Organizations::Policy
    Properties:
      Type: RESOURCE_CONTROL_POLICY
      Name: RCPRestrictOIDCToApprovedProviders
      Description: Deny non approved OIDC providers Org wide
      Content:
        Version: 2012-10-17
        Statement:
          - Sid: GitHubRepo
            Effect: Deny
            Principal: '*'
            Action:
              - 'sts:AssumeRoleWithWebIdentity'
            Resource: '*'
            Condition:
             StringNotLike:
               'token.actions.githubusercontent.com:sub': !Sub 'repo:${GitHubRepo}:*'
      TargetIds:
        - !Ref OrganizationRootId

Outputs:
  ResourceControlPoliciesId:
    Description: Resource Control Policies ID
    Value: !Ref ResourceControlPolicies
    Export:
      Name: !Sub "${AWS::StackName}-ResourceControlPolicies-PolicyId"

  RCPRestrictOIDCToApprovedProvidersId:
    Description: RCP Restrict OIDC to Approved Providers ID
    Value: !Ref RCPRestrictOIDCToApprovedProviders
    Export:
      Name: !Sub "${AWS::StackName}-RCPRestrictOIDCToApprovedProviders-PolicyId"
