# SPDX-FileCopyrightText: 2025 Dominik Wombacher <dominik@wombacher.cc>
#
# SPDX-License-Identifier: MIT-0

AWSTemplateFormatVersion: '2010-09-09'
Description: "Service Control Policies for AWS Organizations - Cost optimization policies for logging services (NOT DEPLOYED - see scp-cost.yaml)"

# =============================================================================
# STATUS: PARTIALLY MIGRATED TO scp-cost.yaml
# =============================================================================
#
# MIGRATED (now in scp-cost.yaml):
# - DenySecurityHubActions                        -> DenySecurityHub
# - DenyHighCostCloudWatchFeatures/DenyDetailedMonitoring -> DenyDetailedMonitoring
# - DenyHighCostCloudWatchFeatures/DenyContainerInsightsEnhanced -> DenyContainerInsightsEnhanced
#
# NOT MIGRATED (kept below for reference - risky or low value):
# - DenyHighCostEventBridgeFeatures  (archive/replay useful for debugging, low cost)
# - DenyHighResolutionMetrics        (DANGEROUS - breaks all custom metrics!)
#
# =============================================================================

Parameters:
  OrganizationRootId:
    Type: String
    Description: "AWS Organizations root ID (e.g., r-xxxx)"

Resources:
  # =============================================================================
  # REMAINING POLICIES - NOT MIGRATED (risky or low value)
  # =============================================================================

  # Blocks EventBridge features with storage costs
  # WARNING: Archive and replay are relatively low cost and can be useful for debugging.
  # Schema discovery is also low cost. Consider if this is worth blocking.
  DenyHighCostEventBridgeFeatures:
    DeletionPolicy: Retain
    UpdateReplacePolicy: Retain
    Type: AWS::Organizations::Policy
    Properties:
      Type: SERVICE_CONTROL_POLICY
      Name: DenyHighCostEventBridgeFeatures
      Description: |
        Block EventBridge features with storage costs while allowing pay-per-event usage.
        WARNING: Archive/replay are useful for debugging. Consider carefully.
      Content:
        Version: 2012-10-17
        Statement:
          - Sid: DenyEventArchive
            Effect: Deny
            Action:
              - 'events:CreateArchive'
              - 'events:UpdateArchive'
            Resource: '*'
          - Sid: DenyEventReplay
            Effect: Deny
            Action:
              - 'events:StartReplay'
            Resource: '*'
          - Sid: DenySchemaDiscovery
            Effect: Deny
            Action:
              - 'schemas:StartDiscoverer'
              - 'schemas:CreateDiscoverer'
            Resource: '*'
      TargetIds:
        - !Ref OrganizationRootId

  # DANGER: This policy contains DenyHighResolutionMetrics which blocks ALL PutMetricData!
  # This BREAKS: Lambda custom metrics, application metrics, SDK metrics, everything.
  # DO NOT DEPLOY this policy. Kept only as a warning/reference.
  DenyHighResolutionMetrics:
    DeletionPolicy: Retain
    UpdateReplacePolicy: Retain
    Type: AWS::Organizations::Policy
    Properties:
      Type: SERVICE_CONTROL_POLICY
      Name: DenyHighResolutionMetrics
      Description: |
        DANGER: DO NOT DEPLOY! This blocks ALL cloudwatch:PutMetricData.
        This will break Lambda metrics, custom metrics, and most monitoring.
        Kept only as a reference for what NOT to do.
      Content:
        Version: 2012-10-17
        Statement:
          # DANGER: This blocks ALL custom metrics!
          - Sid: DenyHighResolutionMetrics
            Effect: Deny
            Action:
              - 'cloudwatch:PutMetricData'
            Resource: '*'
      TargetIds:
        - !Ref OrganizationRootId

Outputs:
  DenyHighCostEventBridgeFeaturesPolicyId:
    Description: EventBridge High-Cost Features Deny SCP Policy ID
    Value: !Ref DenyHighCostEventBridgeFeatures
    Export:
      Name: !Sub "${AWS::StackName}-DenyHighCostEventBridgeFeatures-PolicyId"
  DenyHighResolutionMetricsPolicyId:
    Description: High Resolution Metrics Deny SCP Policy ID (DANGEROUS - DO NOT DEPLOY)
    Value: !Ref DenyHighResolutionMetrics
    Export:
      Name: !Sub "${AWS::StackName}-DenyHighResolutionMetrics-PolicyId"
