# SPDX-FileCopyrightText: 2025 Dominik Wombacher <dominik@wombacher.cc>
#
# SPDX-License-Identifier: MIT-0

AWSTemplateFormatVersion: '2010-09-09'
Description: "Service Control Policies for AWS Organizations - Cost optimization policies for ec2 services (NOT DEPLOYED - see scp-cost.yaml)"

# =============================================================================
# STATUS: FULLY MIGRATED TO scp-cost.yaml
# =============================================================================
#
# MIGRATED (now in scp-cost.yaml):
# - DenyRunInstances                              -> DenyEC2Instances
# - DenyExpensiveStorageFeatures/DenyFSx          -> DenyExpensiveStorage
# - DenyExpensiveStorageFeatures/DenyProvisionedIOPS -> DenyNonGP3Volumes
# - DenyExpensiveStorageFeatures/DenyEFSProvisionedThroughput -> DenyEFSProvisionedThroughput
# - DenyExpensiveNetworkingFeatures/DenyNATGateway -> DenyNATGateway
# - DenyExpensiveNetworkingFeatures/DenyVPCInterfaceEndpoints -> DenyVPCInterfaceEndpoints
#
# NOT MIGRATED (kept below for reference - may need in specific cases):
# - DenyLoadBalancers (may need ALB for WebSockets, complex routing)
#
# =============================================================================

Parameters:
  OrganizationRootId:
    Type: String
    Description: "AWS Organizations root ID (e.g., r-xxxx)"

Resources:
  # =============================================================================
  # REMAINING POLICIES - NOT MIGRATED (may need in specific cases)
  # =============================================================================

  # Blocks load balancer creation
  # WARNING: May need ALB for WebSockets, gRPC, or complex routing that
  # API Gateway HTTP APIs don't support.
  DenyLoadBalancers:
    DeletionPolicy: Retain
    UpdateReplacePolicy: Retain
    Type: AWS::Organizations::Policy
    Properties:
      Type: SERVICE_CONTROL_POLICY
      Name: DenyLoadBalancers
      Description: |
        Block load balancer creation to force API Gateway usage.
        WARNING: May need ALB for WebSockets or complex routing. Review before deploying.
      Content:
        Version: 2012-10-17
        Statement:
          - Sid: DenyLoadBalancers
            Effect: Deny
            Action:
              - 'elasticloadbalancing:CreateLoadBalancer'
            Resource: '*'
      TargetIds:
        - !Ref OrganizationRootId

Outputs:
  DenyLoadBalancersPolicyId:
    Description: Load Balancers Deny SCP Policy ID
    Value: !Ref DenyLoadBalancers
    Export:
      Name: !Sub "${AWS::StackName}-DenyLoadBalancers-PolicyId"
