# SPDX-FileCopyrightText: 2025 Dominik Wombacher <dominik@wombacher.cc>
#
# SPDX-License-Identifier: MIT-0

AWSTemplateFormatVersion: '2010-09-09'
Description: "Service Control Policies for AWS Organizations - Cost optimization policies (NOT DEPLOYED - see scp-cost.yaml)"

# =============================================================================
# STATUS: PARTIALLY MIGRATED TO scp-cost.yaml
# =============================================================================
#
# MIGRATED (now in scp-cost.yaml):
# - DenyRDSAndAurora         -> DenyExpensiveDatabases
# - DenyElastiCache          -> DenyExpensiveDatabases
# - DenyRedshift             -> DenyExpensiveDatabases
# - DenyOpenSearch           -> DenyExpensiveDatabases
# - DenyMemoryDB             -> DenyExpensiveDatabases
# - DenyDocumentDB           -> DenyExpensiveDatabases
# - DenyNeptune              -> DenyExpensiveDatabases
# - DenyKinesis              -> DenyStreamingAndMessaging
# - DenyMSK                  -> DenyStreamingAndMessaging
# - DenyEKS                  -> DenyContainersAndBigData
# - DenyEMR                  -> DenyContainersAndBigData
#
# NOT MIGRATED (kept below for reference - considered too risky/edge case):
# - DenyECSPersistentServices  (partial ECS block is confusing, may break Fargate tasks)
#
# =============================================================================

Parameters:
  OrganizationRootId:
    Type: String
    Description: "AWS Organizations root ID (e.g., r-xxxx)"

Resources:
  # =============================================================================
  # REMAINING POLICIES - NOT MIGRATED (risky or edge case)
  # =============================================================================

  # Blocks persistent ECS services
  # WARNING: This is a partial block that may be confusing. ECS with Fargate
  # can be used in a serverless way (tasks), but services run 24/7.
  # NOT RECOMMENDED for deployment without careful consideration.
  DenyECSPersistentServices:
    DeletionPolicy: Retain
    UpdateReplacePolicy: Retain
    Type: AWS::Organizations::Policy
    Properties:
      Type: SERVICE_CONTROL_POLICY
      Name: DenyECSPersistentServices
      Description: |
        Block persistent ECS services to prevent 24/7 container costs.
        WARNING: May break legitimate Fargate usage. Consider carefully before deploying.
      Content:
        Version: 2012-10-17
        Statement:
          - Sid: DenyECSPersistentServices
            Effect: Deny
            Action:
              - 'ecs:CreateCluster'
              - 'ecs:CreateService'
              - 'ecs:UpdateService'
              - 'ecs:CreateCapacityProvider'
              - 'ecs:PutClusterCapacityProviders'
            Resource: '*'
      TargetIds:
        - !Ref OrganizationRootId

Outputs:
  DenyECSPersistentServicesPolicyId:
    Description: ECS Persistent Services Deny SCP Policy ID
    Value: !Ref DenyECSPersistentServices
    Export:
      Name: !Sub "${AWS::StackName}-DenyECSPersistentServices-PolicyId"
