# SPDX-FileCopyrightText: 2025 Dominik Wombacher <dominik@wombacher.cc>
#
# SPDX-License-Identifier: MIT-0

AWSTemplateFormatVersion: '2010-09-09'
Description: "Service Control Policies - Cost optimization"

Parameters:
  OrganizationRootId:
    Type: String
    Description: "AWS Organizations root ID (e.g., r-xxxx)"

Resources:
  DenyExpensiveServices:
    DeletionPolicy: Retain
    UpdateReplacePolicy: Retain
    Type: AWS::Organizations::Policy
    Properties:
      Type: SERVICE_CONTROL_POLICY
      Name: DenyExpensiveServices
      Description: "Block services with monthly base costs. Enforce pay-per-use serverless only."
      Content:
        Version: 2012-10-17
        Statement:
          # Block EC2 - use Lambda/Fargate instead
          - Sid: DenyEC2Instances
            Effect: Deny
            Action:
              - 'ec2:RunInstances'
            Resource: '*'

          # Block databases with hourly costs - use DynamoDB on-demand instead
          - Sid: DenyExpensiveDatabases
            Effect: Deny
            Action:
              - 'rds:*'
              - 'elasticache:*'
              - 'redshift:*'
              - 'redshift-data:*'
              - 'redshift-serverless:*'
              - 'es:*'
              - 'opensearch:*'
              - 'memorydb:*'
              - 'docdb:*'
              - 'neptune:*'
              - 'neptune-db:*'
              - 'dax:*'
            Resource: '*'

          # Block streaming with hourly costs - use SQS/SNS/EventBridge instead
          - Sid: DenyStreamingAndMessaging
            Effect: Deny
            Action:
              - 'kinesis:*'
              - 'kinesisanalytics:*'
              - 'kinesisanalyticsv2:*'
              - 'kinesisvideo:*'
              - 'kafka:*'
              - 'kafka-cluster:*'
              - 'mq:*'
            Resource: '*'

          # Block container orchestration with base costs
          - Sid: DenyContainersAndBigData
            Effect: Deny
            Action:
              - 'eks:*'
              - 'emr:*'
              - 'emr-containers:*'
              - 'emr-serverless:*'
            Resource: '*'

          # Block FSx - high base costs
          - Sid: DenyExpensiveStorage
            Effect: Deny
            Action:
              - 'fsx:*'
            Resource: '*'

          # Force gp3 volumes - cheapest and best performance
          - Sid: DenyNonGP3Volumes
            Effect: Deny
            Action:
              - 'ec2:CreateVolume'
              - 'ec2:ModifyVolume'
            Resource: '*'
            Condition:
              StringNotEquals:
                'ec2:VolumeType': 'gp3'

          # Block EFS provisioned throughput - bursting mode is free
          - Sid: DenyEFSProvisionedThroughput
            Effect: Deny
            Action:
              - 'elasticfilesystem:CreateFileSystem'
              - 'elasticfilesystem:UpdateFileSystem'
            Resource: '*'
            Condition:
              StringEquals:
                'elasticfilesystem:ThroughputMode': 'provisioned'

          # Block NAT Gateway - $32/month base + data charges
          - Sid: DenyNATGateway
            Effect: Deny
            Action:
              - 'ec2:CreateNatGateway'
            Resource: '*'

          # Block load balancers - no use case without EC2/EKS, use API Gateway
          - Sid: DenyLoadBalancers
            Effect: Deny
            Action:
              - 'elasticloadbalancing:CreateLoadBalancer'
            Resource: '*'

          # Block VPC interface endpoints - $7/month each, allow free S3/DynamoDB gateways
          - Sid: DenyVPCInterfaceEndpoints
            Effect: Deny
            Action:
              - 'ec2:CreateVpcEndpoint'
            Resource: '*'
            Condition:
              StringNotEquals:
                'ec2:VpceServiceName':
                  - 'com.amazonaws.*.s3'
                  - 'com.amazonaws.*.dynamodb'

          # Block Lambda provisioned concurrency - hourly cost even when idle
          - Sid: DenyLambdaProvisionedConcurrency
            Effect: Deny
            Action:
              - 'lambda:PutProvisionedConcurrencyConfig'
            Resource: '*'

          # Block Lambda provisioned event source mapping - hourly polling cost
          - Sid: DenyLambdaProvisionedESM
            Effect: Deny
            Action:
              - 'lambda:CreateEventSourceMapping'
              - 'lambda:UpdateEventSourceMapping'
            Resource: '*'
            Condition:
              'Null':
                'lambda:ProvisionedPollerConfig': 'false'

          # Block DynamoDB reserved capacity - upfront commitment
          - Sid: DenyDynamoDBReservedCapacity
            Effect: Deny
            Action:
              - 'dynamodb:PurchaseReservedCapacityOfferings'
            Resource: '*'

          # Block DynamoDB global tables - multiplies costs per region
          - Sid: DenyDynamoDBGlobalTables
            Effect: Deny
            Action:
              - 'dynamodb:CreateGlobalTable'
              - 'dynamodb:UpdateGlobalTable'
              - 'dynamodb:CreateTableReplica'
            Resource: '*'

          # Block private API Gateway endpoints - $7/month per VPC endpoint
          - Sid: DenyAPIGatewayVPCEndpoints
            Effect: Deny
            Action:
              - 'ec2:CreateVpcEndpoint'
            Resource: '*'
            Condition:
              StringEquals:
                'ec2:VpceServiceName': 'com.amazonaws.*.execute-api'

          # Block detailed EC2 monitoring - per-metric costs
          - Sid: DenyDetailedMonitoring
            Effect: Deny
            Action:
              - 'ec2:MonitorInstances'
            Resource: '*'

          # Block enhanced container insights - higher metric costs
          - Sid: DenyContainerInsightsEnhanced
            Effect: Deny
            Action:
              - 'ecs:PutAccountSetting'
              - 'eks:UpdateClusterConfig'
            Resource: '*'
            Condition:
              StringLike:
                'ecs:container-insights': 'enhanced'

          # Block Bedrock provisioned throughput - hourly commitment
          - Sid: DenyBedrockProvisionedThroughput
            Effect: Deny
            Action:
              - 'bedrock:CreateProvisionedModelThroughput'
              - 'bedrock:UpdateProvisionedModelThroughput'
            Resource: '*'

          # Block Bedrock custom models - training and hosting costs
          - Sid: DenyBedrockCustomModels
            Effect: Deny
            Action:
              - 'bedrock:CreateModelCustomizationJob'
              - 'bedrock:CreateModelImportJob'
            Resource: '*'

          # Block Bedrock marketplace models - additional licensing costs
          - Sid: DenyBedrockMarketplace
            Effect: Deny
            Action:
              - 'bedrock:CreateMarketplaceModelEndpoint'
              - 'bedrock:RegisterMarketplaceModelEndpoint'
            Resource: '*'

          # Block EventBridge archives - storage costs accumulate if forgotten
          - Sid: DenyEventBridgeArchive
            Effect: Deny
            Action:
              - 'events:CreateArchive'
              - 'events:UpdateArchive'
            Resource: '*'

          # Block EventBridge replay - requires archive which has storage costs
          - Sid: DenyEventBridgeReplay
            Effect: Deny
            Action:
              - 'events:StartReplay'
            Resource: '*'

          # Block schema discovery - per-event costs
          - Sid: DenySchemaDiscovery
            Effect: Deny
            Action:
              - 'schemas:StartDiscoverer'
              - 'schemas:CreateDiscoverer'
            Resource: '*'

          # Block Security Hub - per-check costs
          - Sid: DenySecurityHub
            Effect: Deny
            Action:
              - 'securityhub:*'
            Resource: '*'

          # Block expensive commitments and subscriptions
          - Sid: DenyExpensiveCommitments
            Effect: Deny
            Action:
              - 'shield:CreateSubscription'
              - 'acm-pca:CreateCertificateAuthority'
              - 'savingsplans:CreateSavingsPlan'
              - 'ec2:ModifyReservedInstances'
              - 'ec2:PurchaseHostReservation'
              - 'ec2:PurchaseReservedInstancesOffering'
              - 'ec2:PurchaseScheduledInstances'
              - 'aws-marketplace:Subscribe'
              - 'aws-marketplace:AcceptAgreementApprovalRequest'
              - 'outposts:CreateOutpost'
              - 'snowball:CreateCluster'
              - 'route53domains:RegisterDomain'
              - 'route53domains:RenewDomain'
              - 'route53domains:TransferDomain'
            Resource: '*'

      TargetIds:
        - !Ref OrganizationRootId

Outputs:
  DenyExpensiveServicesPolicyId:
    Description: Consolidated Cost Optimization SCP Policy ID
    Value: !Ref DenyExpensiveServices
    Export:
      Name: !Sub "${AWS::StackName}-DenyExpensiveServices-PolicyId"
