# SPDX-FileCopyrightText: 2025 Dominik Wombacher <dominik@wombacher.cc>
#
# SPDX-License-Identifier: MIT-0

AWSTemplateFormatVersion: '2010-09-09'
Description: "Service Control Policies for AWS Organizations - Cost optimization policies for logging services (NOT DEPLOYED - see scp-cost.yaml)"

# =============================================================================
# STATUS: PARTIALLY MIGRATED TO scp-cost.yaml
# =============================================================================
#
# MIGRATED (now in scp-cost.yaml):
# - DenySecurityHubActions  -> DenySecurityHub
#
# NOT MIGRATED (kept below for reference - considered too risky):
# - DenyHighCostEventBridgeFeatures  (archive/replay may be useful, low cost)
# - DenyHighCostCloudWatchFeatures   (BREAKS cloudwatch:PutMetricData - kills all custom metrics!)
#
# =============================================================================

Parameters:
  OrganizationRootId:
    Type: String
    Description: "AWS Organizations root ID (e.g., r-xxxx)"

Resources:
  # =============================================================================
  # REMAINING POLICIES - NOT MIGRATED (risky or breaks things)
  # =============================================================================

  # Blocks EventBridge features with storage costs
  # WARNING: Archive and replay are relatively low cost and can be useful for debugging.
  # Schema discovery is also low cost. Consider if this is worth blocking.
  DenyHighCostEventBridgeFeatures:
    DeletionPolicy: Retain
    UpdateReplacePolicy: Retain
    Type: AWS::Organizations::Policy
    Properties:
      Type: SERVICE_CONTROL_POLICY
      Name: DenyHighCostEventBridgeFeatures
      Description: |
        Block EventBridge features with storage costs while allowing pay-per-event usage.
        WARNING: Archive/replay are useful for debugging. Consider carefully.
      Content:
        Version: 2012-10-17
        Statement:
          - Sid: DenyEventArchive
            Effect: Deny
            Action:
              - 'events:CreateArchive'
              - 'events:UpdateArchive'
            Resource: '*'
          - Sid: DenyEventReplay
            Effect: Deny
            Action:
              - 'events:StartReplay'
            Resource: '*'
          - Sid: DenySchemaDiscovery
            Effect: Deny
            Action:
              - 'schemas:StartDiscoverer'
              - 'schemas:CreateDiscoverer'
            Resource: '*'
      TargetIds:
        - !Ref OrganizationRootId

  # Restricts high-cost CloudWatch features
  # DANGER: DenyHighResolutionMetrics blocks cloudwatch:PutMetricData entirely!
  # This BREAKS: Lambda custom metrics, application metrics, SDK metrics, everything.
  # DO NOT DEPLOY without removing DenyHighResolutionMetrics statement.
  DenyHighCostCloudWatchFeatures:
    DeletionPolicy: Retain
    UpdateReplacePolicy: Retain
    Type: AWS::Organizations::Policy
    Properties:
      Type: SERVICE_CONTROL_POLICY
      Name: DenyHighCostCloudWatchFeatures
      Description: |
        DANGER: Contains DenyHighResolutionMetrics which blocks ALL PutMetricData.
        This will break Lambda metrics, custom metrics, and most monitoring.
        DO NOT DEPLOY without careful review and modification.
      Content:
        Version: 2012-10-17
        Statement:
          - Sid: DenyDetailedMonitoring
            Effect: Deny
            Action:
              - 'ec2:MonitorInstances'
              - 'rds:ModifyDBInstance'
              - 'elasticloadbalancing:ModifyLoadBalancerAttributes'
            Resource: '*'
            Condition:
              StringEquals:
                'ec2:DetailedMonitoring': 'true'
          - Sid: DenyContainerInsightsEnhanced
            Effect: Deny
            Action:
              - 'ecs:PutAccountSetting'
              - 'eks:UpdateClusterConfig'
            Resource: '*'
            Condition:
              StringLike:
                'ecs:container-insights': 'enhanced'
          # DANGER: This blocks ALL custom metrics!
          - Sid: DenyHighResolutionMetrics
            Effect: Deny
            Action:
              - 'cloudwatch:PutMetricData'
            Resource: '*'
      TargetIds:
        - !Ref OrganizationRootId

Outputs:
  DenyHighCostEventBridgeFeaturesPolicyId:
    Description: EventBridge High-Cost Features Deny SCP Policy ID
    Value: !Ref DenyHighCostEventBridgeFeatures
    Export:
      Name: !Sub "${AWS::StackName}-DenyHighCostEventBridgeFeatures-PolicyId"
  DenyHighCostCloudWatchFeaturesPolicyId:
    Description: CloudWatch High-Cost Features Deny SCP Policy ID
    Value: !Ref DenyHighCostCloudWatchFeatures
    Export:
      Name: !Sub "${AWS::StackName}-DenyHighCostCloudWatchFeatures-PolicyId"
