# SPDX-FileCopyrightText: 2025 Dominik Wombacher <dominik@wombacher.cc>
#
# SPDX-License-Identifier: MIT-0

AWSTemplateFormatVersion: '2010-09-09'
Description: "Service Control Policies for AWS Organizations - Cost optimization policies for logging services (MOSTLY MIGRATED - see scp-cost.yaml)"

# =============================================================================
# STATUS: MOSTLY MIGRATED TO scp-cost.yaml
# =============================================================================
#
# MIGRATED (now in scp-cost.yaml):
# - DenySecurityHubActions                        -> DenySecurityHub
# - DenyHighCostCloudWatchFeatures/DenyDetailedMonitoring -> DenyDetailedMonitoring
# - DenyHighCostCloudWatchFeatures/DenyContainerInsightsEnhanced -> DenyContainerInsightsEnhanced
# - DenyHighCostEventBridgeFeatures/DenyEventArchive -> DenyEventBridgeArchive
# - DenyHighCostEventBridgeFeatures/DenyEventReplay -> DenyEventBridgeReplay
# - DenyHighCostEventBridgeFeatures/DenySchemaDiscovery -> DenySchemaDiscovery
#
# NOT MIGRATED (kept below as WARNING - DO NOT DEPLOY):
# - DenyHighResolutionMetrics (DANGEROUS - breaks all custom metrics!)
#
# =============================================================================

Parameters:
  OrganizationRootId:
    Type: String
    Description: "AWS Organizations root ID (e.g., r-xxxx)"

Resources:
  # =============================================================================
  # DANGEROUS POLICY - DO NOT DEPLOY
  # Kept only as a reference for what NOT to do
  # =============================================================================

  # DANGER: This policy blocks ALL cloudwatch:PutMetricData!
  # This BREAKS: Lambda custom metrics, application metrics, SDK metrics, everything.
  # DO NOT DEPLOY this policy. Kept only as a warning/reference.
  DenyHighResolutionMetrics:
    DeletionPolicy: Retain
    UpdateReplacePolicy: Retain
    Type: AWS::Organizations::Policy
    Properties:
      Type: SERVICE_CONTROL_POLICY
      Name: DenyHighResolutionMetrics
      Description: |
        DANGER: DO NOT DEPLOY! This blocks ALL cloudwatch:PutMetricData.
        This will break Lambda metrics, custom metrics, and most monitoring.
        Kept only as a reference for what NOT to do.
      Content:
        Version: 2012-10-17
        Statement:
          # DANGER: This blocks ALL custom metrics!
          - Sid: DenyHighResolutionMetrics
            Effect: Deny
            Action:
              - 'cloudwatch:PutMetricData'
            Resource: '*'
      TargetIds:
        - !Ref OrganizationRootId

Outputs:
  DenyHighResolutionMetricsPolicyId:
    Description: High Resolution Metrics Deny SCP Policy ID (DANGEROUS - DO NOT DEPLOY)
    Value: !Ref DenyHighResolutionMetrics
    Export:
      Name: !Sub "${AWS::StackName}-DenyHighResolutionMetrics-PolicyId"
