# SPDX-FileCopyrightText: 2025 Dominik Wombacher <dominik@wombacher.cc>
#
# SPDX-License-Identifier: MIT-0

AWSTemplateFormatVersion: '2010-09-09'
Description: "Parent stack that manages the Organization-wide StackSet for baseline resources"

Parameters:
  OrganizationRootId:
    Type: List<String>
    Description: "List of Org Root ID(s) or OU ID(s) to target (e.g. r-ab12, ou-xxxx-yyyyyyyy)"
  StackSetTargetRegions:
    Type: List<String>
    Description: "List of AWS regions where the baseline resources should be deployed (e.g. eu-central-1, eu-west-1)"

Metadata:
  cfn-lint:
    config:
      ignore_checks:
        - E3006 # Global resource

Resources:
  OrgBaselineStackSet:
    Type: AWS::CloudFormation::StackSet
    Properties:
      StackSetName: Organization-Baseline-StackSet
      Description: "Deploys baseline resources across the entire AWS Organization"
      PermissionModel: SERVICE_MANAGED
      AutoDeployment:
        Enabled: true
        RetainStacksOnAccountRemoval: false
      Capabilities:
        - CAPABILITY_NAMED_IAM
      Parameters: []
      TemplateBody: |
        AWSTemplateFormatVersion: '2010-09-09'
        Description: "Organization-wide Baseline Resources"

        Resources:
          # === IAM Account Password Policy ===
          IAMAccountPasswordPolicy:
            Type: AWS::IAM::AccountPasswordPolicy
            Properties:
              MinimumPasswordLength: 32
              RequireLowercaseCharacters: true
              RequireNumbers: true
              RequireSymbols: true
              RequireUppercaseCharacters: true
              AllowUsersToChangePassword: true
              PasswordReusePrevention: 24
              MaxPasswordAge: 90

        Outputs:
          IAMAccountPasswordPolicyId:
            Description: IAM Account Password Policy ID
            Value: !Ref IAMAccountPasswordPolicy
      StackInstancesGroup:
        - DeploymentTargets:
            OrganizationalUnitIds: !Ref OrganizationRootId
          Regions: !Ref StackSetTargetRegions


Outputs:
  StackSetName:
    Description: The name of the Organization-wide baseline StackSet
    Value: !Ref OrgBaselineStackSet
